import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  // Complete Pokemon data for all 151 original Pokemon
  const pokemonData = [
    {
      name: 'Bulbasaur',
      type: 'Grass/Poison',
      height: 0.7,
      weight: 6.9,
      hp: 45,
      attack: 49,
      defense: 49,
      speed: 45,
      specialAttack: 65,
      specialDefense: 65,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png',
      description: 'A strange seed was planted on its back at birth. The plant sprouts and grows with this Pokémon.'
    },
    {
      name: 'Ivysaur',
      type: 'Grass/Poison',
      height: 1.0,
      weight: 13.0,
      hp: 60,
      attack: 62,
      defense: 63,
      speed: 60,
      specialAttack: 80,
      specialDefense: 80,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/2.png',
      description: 'When the bulb on its back grows large, it appears to lose the ability to stand on its hind legs.'
    },
    {
      name: 'Venusaur',
      type: 'Grass/Poison',
      height: 2.0,
      weight: 100.0,
      hp: 80,
      attack: 82,
      defense: 83,
      speed: 80,
      specialAttack: 100,
      specialDefense: 100,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/3.png',
      description: 'Its plant blooms when it is absorbing solar energy. It stays still to absorb as much as possible.'
    },
    {
      name: 'Charmander',
      type: 'Fire',
      height: 0.6,
      weight: 6.0,
      hp: 39,
      attack: 52,
      defense: 43,
      speed: 65,
      specialAttack: 60,
      specialDefense: 50,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/4.png',
      description: 'The flame on its tail shows the strength of its life force. If it is weak, the flame also burns weakly.'
    },
    {
      name: 'Charmeleon',
      type: 'Fire',
      height: 1.1,
      weight: 19.0,
      hp: 58,
      attack: 64,
      defense: 58,
      speed: 80,
      specialAttack: 80,
      specialDefense: 65,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/5.png',
      description: 'It lashes about with its tail to try to inflict damage on its opponent.'
    },
    {
      name: 'Charizard',
      type: 'Fire/Flying',
      height: 1.7,
      weight: 90.5,
      hp: 78,
      attack: 84,
      defense: 78,
      speed: 100,
      specialAttack: 109,
      specialDefense: 85,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/6.png',
      description: 'It spits fire that is hot enough to melt boulders. It may cause forest fires by blowing flames.'
    },
    {
      name: 'Squirtle',
      type: 'Water',
      height: 0.5,
      weight: 5.0,
      hp: 44,
      attack: 48,
      defense: 65,
      speed: 43,
      specialAttack: 50,
      specialDefense: 64,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/7.png',
      description: 'It shelters itself in its shell, then strikes back with its water attacks.'
    },
    {
      name: 'Wartortle',
      type: 'Water',
      height: 1.0,
      weight: 22.5,
      hp: 59,
      attack: 63,
      defense: 80,
      speed: 58,
      specialAttack: 65,
      specialDefense: 80,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/8.png',
      description: 'It is recognized as a symbol of longevity. If its shell is broken, it will die.'
    },
    {
      name: 'Blastoise',
      type: 'Water',
      height: 1.6,
      weight: 85.5,
      hp: 79,
      attack: 83,
      defense: 100,
      speed: 78,
      specialAttack: 85,
      specialDefense: 105,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/9.png',
      description: 'It crushes its foe under its heavy body weight. It uses its bulky body as a weapon.'
    },
    {
      name: 'Caterpie',
      type: 'Bug',
      height: 0.3,
      weight: 2.9,
      hp: 45,
      attack: 30,
      defense: 35,
      speed: 45,
      specialAttack: 20,
      specialDefense: 20,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10.png',
      description: 'It releases a stinking fluid from its antennae to repel predators.'
    },
    {
      name: 'Metapod',
      type: 'Bug',
      height: 0.7,
      weight: 9.9,
      hp: 50,
      attack: 20,
      defense: 55,
      speed: 30,
      specialAttack: 25,
      specialDefense: 25,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/11.png',
      description: 'It is waiting to evolve and gain more power. It only knows how to harden its shell.'
    },
    {
      name: 'Butterfree',
      type: 'Bug/Flying',
      height: 1.1,
      weight: 32.0,
      hp: 60,
      attack: 45,
      defense: 50,
      speed: 70,
      specialAttack: 90,
      specialDefense: 80,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/12.png',
      description: 'It collects honey every day. It has flight patterns that are similar to butterflies.'
    },
    {
      name: 'Weedle',
      type: 'Bug/Poison',
      height: 0.3,
      weight: 3.2,
      hp: 40,
      attack: 35,
      defense: 30,
      speed: 60,
      specialAttack: 20,
      specialDefense: 20,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/13.png',
      description: 'It has a poisonous stinger on its head. It attacks by raising its head and ramming into opponents.'
    },
    {
      name: 'Kakuna',
      type: 'Bug/Poison',
      height: 1.1,
      weight: 22.0,
      hp: 45,
      attack: 25,
      defense: 50,
      speed: 35,
      specialAttack: 25,
      specialDefense: 50,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/14.png',
      description: 'It can only harden its shell. It moves so little that people forget it is there.'
    },
    {
      name: 'Beedrill',
      type: 'Bug/Poison',
      height: 1.0,
      weight: 29.5,
      hp: 65,
      attack: 90,
      defense: 40,
      speed: 75,
      specialAttack: 45,
      specialDefense: 80,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/15.png',
      description: 'It has three poisonous stingers on its forelegs and tail.'
    },
    {
      name: 'Pidgey',
      type: 'Normal/Flying',
      height: 0.3,
      weight: 2.0,
      hp: 40,
      attack: 45,
      defense: 40,
      speed: 56,
      specialAttack: 35,
      specialDefense: 35,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/16.png',
      description: 'It has a small body but can fly very fast.'
    },
    {
      name: 'Pidgeotto',
      type: 'Normal/Flying',
      height: 1.1,
      weight: 30.0,
      hp: 63,
      attack: 60,
      defense: 55,
      speed: 71,
      specialAttack: 50,
      specialDefense: 50,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/17.png',
      description: 'It protects its territory fiercely. It has incredible vision.'
    },
    {
      name: 'Pidgeot',
      type: 'Normal/Flying',
      height: 1.5,
      weight: 39.5,
      hp: 83,
      attack: 80,
      defense: 75,
      speed: 91,
      specialAttack: 70,
      specialDefense: 70,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/18.png',
      description: 'It spreads its gorgeous wings widely to attack enemies.'
    },
    {
      name: 'Rattata',
      type: 'Normal',
      height: 0.3,
      weight: 3.5,
      hp: 30,
      attack: 56,
      defense: 35,
      speed: 72,
      specialAttack: 25,
      specialDefense: 35,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/19.png',
      description: 'It has sharp fangs. It will bite anything.'
    },
    {
      name: 'Raticate',
      type: 'Normal',
      height: 0.7,
      weight: 28.5,
      hp: 75,
      attack: 81,
      defense: 70,
      speed: 77,
      specialAttack: 50,
      specialDefense: 70,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/20.png',
      description: 'It has long whiskers. It uses them to detect its prey.'
    },
    {
      name: 'Spearow',
      type: 'Normal/Flying',
      height: 0.3,
      weight: 2.0,
      hp: 30,
      attack: 40,
      defense: 35,
      speed: 72,
      specialAttack: 30,
      specialDefense: 30,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/21.png',
      description: 'It has short wings but can fly very fast.'
    },
    {
      name: 'Fearow',
      type: 'Normal/Flying',
      height: 1.2,
      weight: 38.0,
      hp: 65,
      attack: 90,
      defense: 65,
      speed: 100,
      specialAttack: 45,
      specialDefense: 55,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/22.png',
      description: 'It has a long neck that sharpak. It can attack from far away.'
    },
    {
      name: 'Ekans',
      type: 'Poison',
      height: 0.7,
      weight: 6.9,
      hp: 35,
      attack: 60,
      defense: 44,
      speed: 55,
      specialAttack: 40,
      specialDefense: 54,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/23.png',
      description: 'It can swallow its prey whole.'
    },
    {
      name: 'Arbok',
      type: 'Poison',
      height: 3.5,
      weight: 65.0,
      hp: 60,
      attack: 85,
      defense: 69,
      speed: 80,
      specialAttack: 65,
      specialDefense: 79,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/24.png',
      description: 'It has a terrifying pattern on its belly.'
    },
    {
      name: 'Pikachu',
      type: 'Electric',
      height: 0.4,
      weight: 6.0,
      hp: 35,
      attack: 55,
      defense: 40,
      speed: 90,
      specialAttack: 50,
      specialDefense: 50,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/25.png',
      description: 'When several of these Pokémon gather, their electricity could build and cause lightning storms.'
    },
    {
      name: 'Raichu',
      type: 'Electric',
      height: 0.8,
      weight: 30.0,
      hp: 60,
      attack: 90,
      defense: 55,
      speed: 110,
      specialAttack: 90,
      specialDefense: 80,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/26.png',
      description: 'Its electric attacks are so powerful they can knock out a helicopter.'
    },
    {
      name: 'Sandshrew',
      type: 'Ground',
      height: 0.6,
      weight: 12.0,
      hp: 50,
      attack: 75,
      defense: 85,
      speed: 40,
      specialAttack: 20,
      specialDefense: 30,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/27.png',
      description: 'It has tough skin that can withstand any attack.'
    },
    {
      name: 'Sandslash',
      type: 'Ground',
      height: 1.0,
      weight: 29.5,
      hp: 75,
      attack: 100,
      defense: 110,
      speed: 65,
      specialAttack: 30,
      specialDefense: 55,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/28.png',
      description: 'It has huge claws that can dig through any ground.'
    },
    {
      name: 'Nidoran♀',
      type: 'Poison',
      height: 0.4,
      weight: 7.0,
      hp: 55,
      attack: 47,
      defense: 52,
      speed: 41,
      specialAttack: 40,
      specialDefense: 40,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/29.png',
      description: 'It has small horns. It uses them to sense its surroundings.'
    },
    {
      name: 'Nidorina',
      type: 'Poison',
      height: 1.1,
      weight: 24.0,
      hp: 70,
      attack: 62,
      defense: 67,
      speed: 56,
      specialAttack: 55,
      specialDefense: 55,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/30.png',
      description: 'It has large horns. It uses them to attack its enemies.'
    },
    {
      name: 'Nidoqueen',
      type: 'Poison/Ground',
      height: 1.3,
      weight: 60.0,
      hp: 90,
      attack: 82,
      defense: 87,
      speed: 76,
      specialAttack: 75,
      specialDefense: 85,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/31.png',
      description: 'It has huge horns. It uses them to attack its enemies.'
    },
    {
      name: 'Nidoran♂',
      type: 'Poison',
      height: 0.5,
      weight: 9.0,
      hp: 46,
      attack: 57,
      defense: 40,
      speed: 50,
      specialAttack: 40,
      specialDefense: 40,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/32.png',
      description: 'It has small horns. It uses them to sense its surroundings.'
    },
    {
      name: 'Nidorino',
      type: 'Poison',
      height: 0.9,
      weight: 19.5,
      hp: 61,
      attack: 72,
      defense: 57,
      speed: 65,
      specialAttack: 55,
      specialDefense: 55,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/33.png',
      description: 'It has large horns. It uses them to attack its enemies.'
    },
    {
      name: 'Nidoking',
      type: 'Poison/Ground',
      height: 1.4,
      weight: 62.0,
      hp: 81,
      attack: 92,
      defense: 77,
      speed: 85,
      specialAttack: 85,
      specialDefense: 75,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/34.png',
      description: 'It has huge horns. It uses them to attack its enemies.'
    },
    {
      name: 'Clefairy',
      type: 'Fairy',
      height: 0.6,
      weight: 7.5,
      hp: 70,
      attack: 45,
      defense: 48,
      speed: 35,
      specialAttack: 60,
      specialDefense: 65,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/35.png',
      description: 'It has small wings. It uses them to fly short distances.'
    },
    {
      name: 'Clefable',
      type: 'Fairy',
      height: 1.6,
      weight: 48.0,
      hp: 95,
      attack: 70,
      defense: 73,
      speed: 60,
      specialAttack: 85,
      specialDefense: 90,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/36.png',
      description: 'It has large wings. It uses them to fly long distances.'
    },
    {
      name: 'Vulpix',
      type: 'Fire',
      height: 0.6,
      weight: 9.9,
      hp: 38,
      attack: 41,
      defense: 40,
      speed: 65,
      specialAttack: 50,
      specialDefense: 65,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/37.png',
      description: 'It has six tails. It uses them to attack its enemies.'
    },
    {
      name: 'Ninetales',
      type: 'Fire',
      height: 1.1,
      weight: 19.9,
      hp: 73,
      attack: 76,
      defense: 75,
      speed: 100,
      specialAttack: 81,
      specialDefense: 100,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/38.png',
      description: 'It has nine tails. It uses them to attack its enemies.'
    },
    {
      name: 'Jigglypuff',
      type: 'Normal/Fairy',
      height: 0.5,
      weight: 5.5,
      hp: 115,
      attack: 45,
      defense: 20,
      speed: 20,
      specialAttack: 45,
      specialDefense: 25,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/39.png',
      description: 'It captivates foes with its huge, round eyes, then it sings a soothing lullaby.'
    },
    {
      name: 'Wigglytuff',
      type: 'Normal/Fairy',
      height: 1.0,
      weight: 12.0,
      hp: 140,
      attack: 70,
      defense: 45,
      speed: 45,
      specialAttack: 75,
      specialDefense: 50,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/40.png',
      description: 'It has large, expressive eyes. It uses them to hypnotize its opponents.'
    },
    {
      name: 'Zubat',
      type: 'Poison/Flying',
      height: 0.8,
      weight: 7.5,
      hp: 40,
      attack: 45,
      defense: 35,
      speed: 55,
      specialAttack: 30,
      specialDefense: 40,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/41.png',
      description: 'It forms colonies in perpetually dark places. It uses ultrasonic waves to identify and approach targets.'
    },
    {
      name: 'Golbat',
      type: 'Poison/Flying',
      height: 1.6,
      weight: 55.0,
      hp: 75,
      attack: 80,
      defense: 70,
      speed: 90,
      specialAttack: 65,
      specialDefense: 75,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/42.png',
      description: 'It has sharp fangs. It uses them to suck blood from its victims.'
    },
    {
      name: 'Oddish',
      type: 'Grass/Poison',
      height: 0.5,
      weight: 5.4,
      hp: 45,
      attack: 50,
      defense: 55,
      speed: 30,
      specialAttack: 75,
      specialDefense: 65,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/43.png',
      description: 'It buries itself in soil to absorb nutrients. It is often mistaken for a clump of weeds.'
    },
    {
      name: 'Gloom',
      type: 'Grass/Poison',
      height: 0.8,
      weight: 8.6,
      hp: 60,
      attack: 65,
      defense: 70,
      speed: 40,
      specialAttack: 85,
      specialDefense: 75,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/44.png',
      description: 'It has a flower on its head. It releases a foul smell to repel predators.'
    },
    {
      name: 'Vileplume',
      type: 'Grass/Poison',
      height: 1.2,
      weight: 18.6,
      hp: 75,
      attack: 80,
      defense: 85,
      speed: 50,
      specialAttack: 100,
      specialDefense: 90,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/45.png',
      description: 'It has a huge flower on its head. It releases toxic spores to paralyze its enemies.'
    },
    {
      name: 'Paras',
      type: 'Bug/Grass',
      height: 0.3,
      weight: 5.4,
      hp: 35,
      attack: 70,
      defense: 55,
      speed: 25,
      specialAttack: 45,
      specialDefense: 55,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/46.png',
      description: 'It has mushrooms on its back. It uses them to absorb nutrients from its host.'
    },
    {
      name: 'Parasect',
      type: 'Bug/Grass',
      height: 1.0,
      weight: 29.5,
      hp: 60,
      attack: 95,
      defense: 80,
      speed: 30,
      specialAttack: 60,
      specialDefense: 80,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/47.png',
      description: 'It has a large mushroom on its back. It uses it to control its host.'
    },
    {
      name: 'Venonat',
      type: 'Bug/Poison',
      height: 1.0,
      weight: 30.0,
      hp: 60,
      attack: 55,
      defense: 50,
      speed: 45,
      specialAttack: 40,
      specialDefense: 55,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/48.png',
      description: 'It has large eyes. It uses them to see in the dark.'
    },
    {
      name: 'Venomoth',
      type: 'Bug/Poison',
      height: 1.5,
      weight: 12.5,
      hp: 70,
      attack: 65,
      defense: 60,
      speed: 90,
      specialAttack: 90,
      specialDefense: 75,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/49.png',
      description: 'It has large wings. It uses them to spread poisonous powder.'
    },
    {
      name: 'Diglett',
      type: 'Ground',
      height: 0.2,
      weight: 0.8,
      hp: 10,
      attack: 55,
      defense: 25,
      speed: 95,
      specialAttack: 35,
      specialDefense: 45,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/50.png',
      description: 'It lives underground. It uses its sharp claws to dig tunnels.'
    },
    {
      name: 'Dugtrio',
      type: 'Ground',
      height: 0.7,
      weight: 33.3,
      hp: 35,
      attack: 80,
      defense: 50,
      speed: 120,
      specialAttack: 50,
      specialDefense: 70,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/51.png',
      description: 'It has three heads. It uses them to dig through the ground.'
    },
    {
      name: 'Meowth',
      type: 'Normal',
      height: 0.4,
      weight: 4.2,
      hp: 40,
      attack: 45,
      defense: 35,
      speed: 90,
      specialAttack: 40,
      specialDefense: 40,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/52.png',
      description: 'It has a coin on its forehead. It uses it to attract mates.'
    },
    {
      name: 'Persian',
      type: 'Normal',
      height: 1.0,
      weight: 32.0,
      hp: 65,
      attack: 70,
      defense: 60,
      speed: 115,
      specialAttack: 65,
      specialDefense: 65,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/53.png',
      description: 'It has a jewel on its forehead. It uses it to hypnotize its opponents.'
    },
    {
      name: 'Psyduck',
      type: 'Water',
      height: 0.8,
      weight: 19.6,
      hp: 50,
      attack: 52,
      defense: 48,
      speed: 55,
      specialAttack: 65,
      specialDefense: 50,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/54.png',
      description: 'It has a headache. It uses psychic powers to relieve the pain.'
    },
    {
      name: 'Golduck',
      type: 'Water',
      height: 1.7,
      weight: 76.6,
      hp: 80,
      attack: 82,
      defense: 78,
      speed: 85,
      specialAttack: 95,
      specialDefense: 80,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/55.png',
      description: 'It has a gem on its forehead. It uses it to focus its psychic powers.'
    },
    {
      name: 'Mankey',
      type: 'Fighting',
      height: 0.5,
      weight: 28.0,
      hp: 40,
      attack: 80,
      defense: 35,
      speed: 70,
      specialAttack: 35,
      specialDefense: 45,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/56.png',
      description: 'It has a short temper. It will attack anything that angers it.'
    },
    {
      name: 'Primeape',
      type: 'Fighting',
      height: 1.0,
      weight: 32.0,
      hp: 65,
      attack: 105,
      defense: 60,
      speed: 95,
      specialAttack: 60,
      specialDefense: 70,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/57.png',
      description: 'It has a very short temper. It will attack anything that moves.'
    },
    {
      name: 'Growlithe',
      type: 'Fire',
      height: 0.7,
      weight: 19.0,
      hp: 55,
      attack: 70,
      defense: 45,
      speed: 60,
      specialAttack: 70,
      specialDefense: 50,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/58.png',
      description: 'It has a keen sense of smell. It uses it to track down criminals.'
    },
    {
      name: 'Arcanine',
      type: 'Fire',
      height: 1.9,
      weight: 155.0,
      hp: 90,
      attack: 110,
      defense: 80,
      speed: 95,
      specialAttack: 100,
      specialDefense: 80,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/59.png',
      description: 'It has a majestic appearance. It is known as the legendary Pokémon.'
    },
    {
      name: 'Poliwag',
      type: 'Water',
      height: 0.6,
      weight: 12.4,
      hp: 40,
      attack: 50,
      defense: 40,
      speed: 90,
      specialAttack: 40,
      specialDefense: 40,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/60.png',
      description: 'It has a spiral on its stomach. It uses it to sense its surroundings.'
    },
    {
      name: 'Poliwhirl',
      type: 'Water',
      height: 1.0,
      weight: 20.0,
      hp: 65,
      attack: 65,
      defense: 65,
      speed: 90,
      specialAttack: 50,
      specialDefense: 50,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/61.png',
      description: 'It has a spiral on its stomach. It uses it to hypnotize its opponents.'
    },
    {
      name: 'Poliwrath',
      type: 'Water/Fighting',
      height: 1.3,
      weight: 54.0,
      hp: 90,
      attack: 85,
      defense: 95,
      speed: 70,
      specialAttack: 70,
      specialDefense: 90,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/62.png',
      description: 'It has a spiral on its stomach. It uses it to focus its energy.'
    },
    {
      name: 'Abra',
      type: 'Psychic',
      height: 0.9,
      weight: 19.5,
      hp: 25,
      attack: 20,
      defense: 15,
      speed: 90,
      specialAttack: 105,
      specialDefense: 55,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/63.png',
      description: 'It sleeps for 18 hours a day. It uses psychic powers to teleport away from danger.'
    },
    {
      name: 'Kadabra',
      type: 'Psychic',
      height: 1.3,
      weight: 56.5,
      hp: 40,
      attack: 35,
      defense: 30,
      speed: 105,
      specialAttack: 120,
      specialDefense: 70,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/64.png',
      description: 'It has a spoon. It uses it to focus its psychic powers.'
    },
    {
      name: 'Alakazam',
      type: 'Psychic',
      height: 1.5,
      weight: 48.0,
      hp: 55,
      attack: 50,
      defense: 45,
      speed: 120,
      specialAttack: 135,
      specialDefense: 85,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/65.png',
      description: 'It has an IQ of 5000. It uses its psychic powers to solve complex problems.'
    },
    {
      name: 'Machop',
      type: 'Fighting',
      height: 0.8,
      weight: 19.5,
      hp: 70,
      attack: 80,
      defense: 50,
      speed: 35,
      specialAttack: 35,
      specialDefense: 35,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/66.png',
      description: 'It has a muscular body. It uses it to lift heavy objects.'
    },
    {
      name: 'Machoke',
      type: 'Fighting',
      height: 1.5,
      weight: 70.5,
      hp: 80,
      attack: 100,
      defense: 70,
      speed: 45,
      specialAttack: 50,
      specialDefense: 60,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/67.png',
      description: 'It has a powerful body. It uses it to crush rocks.'
    },
    {
      name: 'Machamp',
      type: 'Fighting',
      height: 1.6,
      weight: 130.0,
      hp: 90,
      attack: 130,
      defense: 80,
      speed: 55,
      specialAttack: 65,
      specialDefense: 85,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/68.png',
      description: 'It has four arms. It uses them to punch its opponents.'
    },
    {
      name: 'Bellsprout',
      type: 'Grass/Poison',
      height: 0.7,
      weight: 4.0,
      hp: 50,
      attack: 75,
      defense: 35,
      speed: 40,
      specialAttack: 70,
      specialDefense: 30,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/69.png',
      description: 'It has a vine-like body. It uses it to wrap around its opponents.'
    },
    {
      name: 'Weepinbell',
      type: 'Grass/Poison',
      height: 1.0,
      weight: 6.4,
      hp: 65,
      attack: 90,
      defense: 50,
      speed: 55,
      specialAttack: 85,
      specialDefense: 45,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/70.png',
      description: 'It has a bell-shaped head. It uses it to attract prey.'
    },
    {
      name: 'Victreebel',
      type: 'Grass/Poison',
      height: 1.7,
      weight: 15.5,
      hp: 80,
      attack: 105,
      defense: 65,
      speed: 70,
      specialAttack: 100,
      specialDefense: 60,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/71.png',
      description: 'It has a large mouth. It uses it to swallow its prey whole.'
    },
    {
      name: 'Tentacool',
      type: 'Water/Poison',
      height: 0.9,
      weight: 45.5,
      hp: 40,
      attack: 40,
      defense: 35,
      speed: 70,
      specialAttack: 50,
      specialDefense: 100,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/72.png',
      description: 'It has tentacles. It uses them to sting its opponents.'
    },
    {
      name: 'Tentacruel',
      type: 'Water/Poison',
      height: 1.6,
      weight: 55.0,
      hp: 80,
      attack: 70,
      defense: 65,
      speed: 100,
      specialAttack: 80,
      specialDefense: 120,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/73.png',
      description: 'It has long tentacles. It uses them to capture its prey.'
    },
    {
      name: 'Geodude',
      type: 'Rock/Ground',
      height: 0.4,
      weight: 20.0,
      hp: 40,
      attack: 80,
      defense: 100,
      speed: 20,
      specialAttack: 30,
      specialDefense: 30,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/74.png',
      description: 'It has a rock-like body. It uses it to defend itself from attacks.'
    },
    {
      name: 'Graveler',
      type: 'Rock/Ground',
      height: 1.0,
      weight: 105.0,
      hp: 55,
      attack: 95,
      defense: 115,
      speed: 35,
      specialAttack: 45,
      specialDefense: 45,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/75.png',
      description: 'It has a round body. It uses it to roll down hills.'
    },
    {
      name: 'Golem',
      type: 'Rock/Ground',
      height: 1.4,
      weight: 300.0,
      hp: 80,
      attack: 110,
      defense: 130,
      speed: 45,
      specialAttack: 55,
      specialDefense: 65,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/76.png',
      description: 'It has a hard shell. It uses it to protect itself from attacks.'
    },
    {
      name: 'Ponyta',
      type: 'Fire',
      height: 1.0,
      weight: 30.0,
      hp: 50,
      attack: 85,
      defense: 55,
      speed: 90,
      specialAttack: 65,
      specialDefense: 65,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/77.png',
      description: 'It has a fiery mane. It uses it to intimidate its opponents.'
    },
    {
      name: 'Rapidash',
      type: 'Fire',
      height: 1.7,
      weight: 95.0,
      hp: 65,
      attack: 100,
      defense: 70,
      speed: 105,
      specialAttack: 80,
      specialDefense: 80,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/78.png',
      description: 'It has a fiery mane. It uses it to run at incredible speeds.'
    },
    {
      name: 'Slowpoke',
      type: 'Water/Psychic',
      height: 1.2,
      weight: 36.0,
      hp: 90,
      attack: 65,
      defense: 65,
      speed: 15,
      specialAttack: 40,
      specialDefense: 40,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/79.png',
      description: 'It is very slow. It takes 5 seconds for it to feel pain.'
    },
    {
      name: 'Slowbro',
      type: 'Water/Psychic',
      height: 1.6,
      weight: 78.5,
      hp: 95,
      attack: 75,
      defense: 110,
      speed: 30,
      specialAttack: 100,
      specialDefense: 80,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/80.png',
      description: 'It has a Shellder on its tail. It uses it to boost its psychic powers.'
    },
    {
      name: 'Magnemite',
      type: 'Electric/Steel',
      height: 0.3,
      weight: 6.0,
      hp: 25,
      attack: 35,
      defense: 70,
      speed: 45,
      specialAttack: 95,
      specialDefense: 55,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/81.png',
      description: 'It has magnets. It uses them to attach itself to metal objects.'
    },
    {
      name: 'Magneton',
      type: 'Electric/Steel',
      height: 1.0,
      weight: 60.0,
      hp: 50,
      attack: 60,
      defense: 95,
      speed: 70,
      specialAttack: 120,
      specialDefense: 70,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/82.png',
      description: 'It has three magnets. It uses them to generate powerful magnetic fields.'
    },
    {
      name: "Farfetch'd",
      type: 'Normal/Flying',
      height: 0.8,
      weight: 15.0,
      hp: 52,
      attack: 65,
      defense: 55,
      speed: 60,
      specialAttack: 58,
      specialDefense: 62,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/83.png',
      description: 'It has a leek. It uses it as a weapon.'
    },
    {
      name: 'Doduo',
      type: 'Normal/Flying',
      height: 1.4,
      weight: 39.2,
      hp: 35,
      attack: 85,
      defense: 45,
      speed: 75,
      specialAttack: 35,
      specialDefense: 35,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/84.png',
      description: 'It has two heads. It uses them to watch for predators.'
    },
    {
      name: 'Dodrio',
      type: 'Normal/Flying',
      height: 1.8,
      weight: 85.2,
      hp: 60,
      attack: 110,
      defense: 70,
      speed: 100,
      specialAttack: 60,
      specialDefense: 60,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/85.png',
      description: 'It has three heads. It uses them to attack from different angles.'
    },
    {
      name: 'Seel',
      type: 'Water',
      height: 1.1,
      weight: 90.0,
      hp: 65,
      attack: 45,
      defense: 55,
      speed: 45,
      specialAttack: 45,
      specialDefense: 70,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/86.png',
      description: 'It has a horn. It uses it to break through ice.'
    },
    {
      name: 'Dewgong',
      type: 'Water/Ice',
      height: 1.7,
      weight: 120.0,
      hp: 90,
      attack: 70,
      defense: 80,
      speed: 70,
      specialAttack: 70,
      specialDefense: 95,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/87.png',
      description: 'It has a white body. It uses it to blend in with snow.'
    },
    {
      name: 'Grimer',
      type: 'Poison',
      height: 0.9,
      weight: 30.0,
      hp: 80,
      attack: 80,
      defense: 50,
      speed: 25,
      specialAttack: 40,
      specialDefense: 50,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/88.png',
      description: 'It is made of sludge. It uses it to pollute the environment.'
    },
    {
      name: 'Muk',
      type: 'Poison',
      height: 1.2,
      weight: 30.0,
      hp: 105,
      attack: 105,
      defense: 75,
      speed: 50,
      specialAttack: 65,
      specialDefense: 100,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/89.png',
      description: 'It is made of toxic sludge. It uses it to poison its opponents.'
    },
    {
      name: 'Shellder',
      type: 'Water',
      height: 0.3,
      weight: 4.0,
      hp: 30,
      attack: 65,
      defense: 100,
      speed: 40,
      specialAttack: 45,
      specialDefense: 25,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/90.png',
      description: 'It has a hard shell. It uses it to protect itself from attacks.'
    },
    {
      name: 'Cloyster',
      type: 'Water/Ice',
      height: 1.5,
      weight: 132.5,
      hp: 50,
      attack: 95,
      defense: 180,
      speed: 70,
      specialAttack: 85,
      specialDefense: 45,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/91.png',
      description: 'It has a hard shell. It uses it to defend itself from attacks.'
    },
    {
      name: 'Gastly',
      type: 'Ghost/Poison',
      height: 1.3,
      weight: 0.1,
      hp: 30,
      attack: 35,
      defense: 30,
      speed: 80,
      specialAttack: 100,
      specialDefense: 35,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/92.png',
      description: 'It is made of gas. It uses it to suffocate its opponents.'
    },
    {
      name: 'Haunter',
      type: 'Ghost/Poison',
      height: 1.6,
      weight: 0.1,
      hp: 45,
      attack: 50,
      defense: 45,
      speed: 95,
      specialAttack: 115,
      specialDefense: 55,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/93.png',
      description: 'It has hands. It uses them to lick its opponents.'
    },
    {
      name: 'Gengar',
      type: 'Ghost/Poison',
      height: 1.5,
      weight: 40.5,
      hp: 60,
      attack: 65,
      defense: 60,
      speed: 110,
      specialAttack: 130,
      specialDefense: 75,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/94.png',
      description: 'It hides in shadows. It uses them to surprise its opponents.'
    },
    {
      name: 'Onix',
      type: 'Rock/Ground',
      height: 8.8,
      weight: 210.0,
      hp: 35,
      attack: 45,
      defense: 160,
      speed: 70,
      specialAttack: 30,
      specialDefense: 45,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/95.png',
      description: 'It has a long body. It uses it to tunnel through the ground.'
    },
    {
      name: 'Drowzee',
      type: 'Psychic',
      height: 1.0,
      weight: 32.4,
      hp: 60,
      attack: 48,
      defense: 45,
      speed: 42,
      specialAttack: 43,
      specialDefense: 90,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/96.png',
      description: 'It has a long nose. It uses it to sense dreams.'
    },
    {
      name: 'Hypno',
      type: 'Psychic',
      height: 1.6,
      weight: 75.6,
      hp: 85,
      attack: 73,
      defense: 70,
      speed: 67,
      specialAttack: 73,
      specialDefense: 115,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/97.png',
      description: 'It has a pendulum. It uses it to hypnotize its opponents.'
    },
    {
      name: 'Krabby',
      type: 'Water',
      height: 0.4,
      weight: 6.5,
      hp: 30,
      attack: 105,
      defense: 90,
      speed: 50,
      specialAttack: 25,
      specialDefense: 25,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/98.png',
      description: 'It has large pincers. It uses them to crush its prey.'
    },
    {
      name: 'Kingler',
      type: 'Water',
      height: 1.3,
      weight: 60.0,
      hp: 55,
      attack: 130,
      defense: 115,
      speed: 75,
      specialAttack: 50,
      specialDefense: 50,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/99.png',
      description: 'It has a giant pincer. It uses it to crush its prey.'
    },
    {
      name: 'Voltorb',
      type: 'Electric',
      height: 0.5,
      weight: 10.4,
      hp: 40,
      attack: 30,
      defense: 50,
      speed: 100,
      specialAttack: 55,
      specialDefense: 55,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/100.png',
      description: 'It looks like a Poke Ball. It uses it to surprise its opponents.'
    },
    {
      name: 'Electrode',
      type: 'Electric',
      height: 1.2,
      weight: 66.6,
      hp: 60,
      attack: 50,
      defense: 70,
      speed: 140,
      specialAttack: 80,
      specialDefense: 80,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/101.png',
      description: 'It stores electricity. It uses it to shock its opponents.'
    },
    {
      name: 'Exeggcute',
      type: 'Grass/Psychic',
      height: 0.4,
      weight: 2.5,
      hp: 60,
      attack: 40,
      defense: 80,
      speed: 40,
      specialAttack: 60,
      specialDefense: 45,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/102.png',
      description: 'It is made of six eggs. It uses them to confuse its opponents.'
    },
    {
      name: 'Exeggutor',
      type: 'Grass/Psychic',
      height: 2.0,
      weight: 120.0,
      hp: 95,
      attack: 95,
      defense: 85,
      speed: 55,
      specialAttack: 125,
      specialDefense: 65,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/103.png',
      description: 'It has three heads. It uses them to think about complex problems.'
    },
    {
      name: 'Cubone',
      type: 'Ground',
      height: 0.4,
      weight: 6.5,
      hp: 50,
      attack: 50,
      defense: 95,
      speed: 35,
      specialAttack: 40,
      specialDefense: 50,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/104.png',
      description: 'It wears a skull. It uses it to protect itself from attacks.'
    },
    {
      name: 'Marowak',
      type: 'Ground',
      height: 1.0,
      weight: 45.0,
      hp: 60,
      attack: 80,
      defense: 110,
      speed: 45,
      specialAttack: 50,
      specialDefense: 80,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/105.png',
      description: 'It has a bone. It uses it as a weapon.'
    },
    {
      name: 'Hitmonlee',
      type: 'Fighting',
      height: 1.5,
      weight: 49.8,
      hp: 50,
      attack: 120,
      defense: 53,
      speed: 87,
      specialAttack: 35,
      specialDefense: 110,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/106.png',
      description: 'It has long legs. It uses them to kick its opponents.'
    },
    {
      name: 'Hitmonchan',
      type: 'Fighting',
      height: 1.4,
      weight: 50.2,
      hp: 50,
      attack: 105,
      defense: 79,
      speed: 76,
      specialAttack: 35,
      specialDefense: 110,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/107.png',
      description: 'It has boxing gloves. It uses them to punch its opponents.'
    },
    {
      name: 'Lickitung',
      type: 'Normal',
      height: 1.2,
      weight: 65.5,
      hp: 90,
      attack: 55,
      defense: 75,
      speed: 30,
      specialAttack: 60,
      specialDefense: 75,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/108.png',
      description: 'It has a long tongue. It uses it to lick its opponents.'
    },
    {
      name: 'Koffing',
      type: 'Poison',
      height: 0.6,
      weight: 1.0,
      hp: 40,
      attack: 65,
      defense: 95,
      speed: 35,
      specialAttack: 60,
      specialDefense: 45,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/109.png',
      description: 'It is made of gas. It uses it to poison its opponents.'
    },
    {
      name: 'Weezing',
      type: 'Poison',
      height: 1.2,
      weight: 9.5,
      hp: 65,
      attack: 90,
      defense: 120,
      speed: 60,
      specialAttack: 85,
      specialDefense: 70,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/110.png',
      description: 'It has two heads. It uses them to double the poison.'
    },
    {
      name: 'Rhyhorn',
      type: 'Ground/Rock',
      height: 1.0,
      weight: 115.0,
      hp: 80,
      attack: 85,
      defense: 95,
      speed: 25,
      specialAttack: 30,
      specialDefense: 30,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/111.png',
      description: 'It has a hard hide. It uses it to charge at its opponents.'
    },
    {
      name: 'Rhydon',
      type: 'Ground/Rock',
      height: 1.9,
      weight: 120.0,
      hp: 105,
      attack: 130,
      defense: 120,
      speed: 40,
      specialAttack: 45,
      specialDefense: 45,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/112.png',
      description: 'It has a drill horn. It uses it to bore through rocks.'
    },
    {
      name: 'Chansey',
      type: 'Normal',
      height: 1.1,
      weight: 34.6,
      hp: 250,
      attack: 5,
      defense: 5,
      speed: 50,
      specialAttack: 35,
      specialDefense: 105,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/113.png',
      description: 'It has a pouch. It uses it to carry eggs.'
    },
    {
      name: 'Tangela',
      type: 'Grass',
      height: 1.0,
      weight: 35.0,
      hp: 65,
      attack: 55,
      defense: 115,
      speed: 60,
      specialAttack: 100,
      specialDefense: 40,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/114.png',
      description: 'It has vines. It uses them to wrap around its opponents.'
    },
    {
      name: 'Kangaskhan',
      type: 'Normal',
      height: 2.2,
      weight: 80.0,
      hp: 105,
      attack: 95,
      defense: 80,
      speed: 90,
      specialAttack: 40,
      specialDefense: 80,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/115.png',
      description: 'It has a baby in its pouch. It uses it to protect its young.'
    },
    {
      name: 'Horsea',
      type: 'Water',
      height: 0.4,
      weight: 8.0,
      hp: 30,
      attack: 40,
      defense: 70,
      speed: 60,
      specialAttack: 70,
      specialDefense: 25,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/116.png',
      description: 'It has a snout. It uses it to shoot ink at its opponents.'
    },
    {
      name: 'Seadra',
      type: 'Water',
      height: 1.2,
      weight: 25.0,
      hp: 55,
      attack: 65,
      defense: 95,
      speed: 85,
      specialAttack: 95,
      specialDefense: 45,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/117.png',
      description: 'It has a sharp snout. It uses it to stab its opponents.'
    },
    {
      name: 'Goldeen',
      type: 'Water',
      height: 0.6,
      weight: 15.0,
      hp: 45,
      attack: 67,
      defense: 60,
      speed: 63,
      specialAttack: 35,
      specialDefense: 50,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/118.png',
      description: 'It has a horn. It uses it to ram its opponents.'
    },
    {
      name: 'Seaking',
      type: 'Water',
      height: 1.3,
      weight: 39.0,
      hp: 80,
      attack: 92,
      defense: 65,
      speed: 68,
      specialAttack: 65,
      specialDefense: 80,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/119.png',
      description: 'It has a large horn. It uses it to defend its territory.'
    },
    {
      name: 'Staryu',
      type: 'Water',
      height: 0.8,
      weight: 34.5,
      hp: 30,
      attack: 45,
      defense: 55,
      speed: 85,
      specialAttack: 70,
      specialDefense: 55,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/120.png',
      description: 'It has a core. It uses it to regenerate its body.'
    },
    {
      name: 'Starmie',
      type: 'Water/Psychic',
      height: 1.1,
      weight: 80.0,
      hp: 60,
      attack: 75,
      defense: 85,
      speed: 115,
      specialAttack: 100,
      specialDefense: 85,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/121.png',
      description: 'It has a core. It uses it to shoot lasers at its opponents.'
    },
    {
      name: 'Mr. Mime',
      type: 'Psychic/Fairy',
      height: 1.3,
      weight: 54.5,
      hp: 40,
      attack: 45,
      defense: 65,
      speed: 90,
      specialAttack: 100,
      specialDefense: 120,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/122.png',
      description: 'It has gloves. It uses them to create invisible walls.'
    },
    {
      name: 'Scyther',
      type: 'Bug/Flying',
      height: 1.5,
      weight: 56.0,
      hp: 70,
      attack: 110,
      defense: 80,
      speed: 105,
      specialAttack: 55,
      specialDefense: 80,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/123.png',
      description: 'It has scythes. It uses them to cut through anything.'
    },
    {
      name: 'Jynx',
      type: 'Ice/Psychic',
      height: 1.4,
      weight: 40.6,
      hp: 65,
      attack: 50,
      defense: 35,
      speed: 95,
      specialAttack: 115,
      specialDefense: 95,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/124.png',
      description: 'It has a kiss. It uses it to freeze its opponents.'
    },
    {
      name: 'Electabuzz',
      type: 'Electric',
      height: 1.1,
      weight: 30.0,
      hp: 65,
      attack: 83,
      defense: 57,
      speed: 105,
      specialAttack: 95,
      specialDefense: 85,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/125.png',
      description: 'It has electricity. It uses it to shock its opponents.'
    },
    {
      name: 'Magmar',
      type: 'Fire',
      height: 1.3,
      weight: 44.5,
      hp: 65,
      attack: 95,
      defense: 57,
      speed: 93,
      specialAttack: 100,
      specialDefense: 85,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/126.png',
      description: 'It has fire. It uses it to burn its opponents.'
    },
    {
      name: 'Pinsir',
      type: 'Bug',
      height: 1.5,
      weight: 55.0,
      hp: 65,
      attack: 125,
      defense: 100,
      speed: 85,
      specialAttack: 55,
      specialDefense: 70,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/127.png',
      description: 'It has pincers. It uses them to crush its opponents.'
    },
    {
      name: 'Tauros',
      type: 'Normal',
      height: 1.4,
      weight: 88.4,
      hp: 75,
      attack: 100,
      defense: 95,
      speed: 110,
      specialAttack: 40,
      specialDefense: 70,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/128.png',
      description: 'It has horns. It uses them to charge at its opponents.'
    },
    {
      name: 'Magikarp',
      type: 'Water',
      height: 0.9,
      weight: 10.0,
      hp: 20,
      attack: 10,
      defense: 55,
      speed: 80,
      specialAttack: 15,
      specialDefense: 20,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/129.png',
      description: 'It is weak. It uses splash to jump around.'
    },
    {
      name: 'Gyarados',
      type: 'Water/Flying',
      height: 6.5,
      weight: 235.0,
      hp: 95,
      attack: 125,
      defense: 79,
      speed: 81,
      specialAttack: 60,
      specialDefense: 100,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/130.png',
      description: 'It is powerful. It uses its strength to destroy cities.'
    },
    {
      name: 'Lapras',
      type: 'Water/Ice',
      height: 2.5,
      weight: 220.0,
      hp: 130,
      attack: 85,
      defense: 80,
      speed: 60,
      specialAttack: 85,
      specialDefense: 95,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/131.png',
      description: 'It has a shell. It uses it to carry people across water.'
    },
    {
      name: 'Ditto',
      type: 'Normal',
      height: 0.3,
      weight: 4.0,
      hp: 48,
      attack: 48,
      defense: 48,
      speed: 48,
      specialAttack: 48,
      specialDefense: 48,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/132.png',
      description: 'It can transform. It uses it to copy its opponents.'
    },
    {
      name: 'Eevee',
      type: 'Normal',
      height: 0.3,
      weight: 6.5,
      hp: 55,
      attack: 55,
      defense: 50,
      speed: 55,
      specialAttack: 45,
      specialDefense: 65,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/133.png',
      description: 'It can evolve. It uses it to adapt to its environment.'
    },
    {
      name: 'Vaporeon',
      type: 'Water',
      height: 1.0,
      weight: 29.0,
      hp: 130,
      attack: 65,
      defense: 60,
      speed: 65,
      specialAttack: 110,
      specialDefense: 95,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/134.png',
      description: 'It has fins. It uses them to swim quickly.'
    },
    {
      name: 'Jolteon',
      type: 'Electric',
      height: 0.8,
      weight: 24.5,
      hp: 65,
      attack: 65,
      defense: 60,
      speed: 130,
      specialAttack: 110,
      specialDefense: 95,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/135.png',
      description: 'It has spines. It uses them to shoot electricity.'
    },
    {
      name: 'Flareon',
      type: 'Fire',
      height: 0.9,
      weight: 25.0,
      hp: 65,
      attack: 130,
      defense: 60,
      speed: 65,
      specialAttack: 95,
      specialDefense: 110,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/136.png',
      description: 'It has fur. It uses it to store heat.'
    },
    {
      name: 'Porygon',
      type: 'Normal',
      height: 0.8,
      weight: 36.5,
      hp: 65,
      attack: 60,
      defense: 70,
      speed: 40,
      specialAttack: 85,
      specialDefense: 75,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/137.png',
      description: 'It is digital. It uses it to enter computers.'
    },
    {
      name: 'Omanyte',
      type: 'Rock/Water',
      height: 0.4,
      weight: 7.5,
      hp: 35,
      attack: 40,
      defense: 100,
      speed: 35,
      specialAttack: 90,
      specialDefense: 55,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/138.png',
      description: 'It has a shell. It uses it to protect itself from attacks.'
    },
    {
      name: 'Omastar',
      type: 'Rock/Water',
      height: 1.0,
      weight: 35.0,
      hp: 70,
      attack: 60,
      defense: 125,
      speed: 55,
      specialAttack: 115,
      specialDefense: 70,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/139.png',
      description: 'It has a sharp shell. It uses it to stab its opponents.'
    },
    {
      name: 'Kabuto',
      type: 'Rock/Water',
      height: 0.5,
      weight: 11.5,
      hp: 30,
      attack: 80,
      defense: 90,
      speed: 55,
      specialAttack: 55,
      specialDefense: 45,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/140.png',
      description: 'It has a hard shell. It uses it to protect itself from attacks.'
    },
    {
      name: 'Kabutops',
      type: 'Rock/Water',
      height: 1.3,
      weight: 40.5,
      hp: 60,
      attack: 115,
      defense: 105,
      speed: 80,
      specialAttack: 65,
      specialDefense: 70,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/141.png',
      description: 'It has scythes. It uses them to cut through anything.'
    },
    {
      name: 'Aerodactyl',
      type: 'Rock/Flying',
      height: 1.8,
      weight: 59.0,
      hp: 80,
      attack: 105,
      defense: 65,
      speed: 130,
      specialAttack: 60,
      specialDefense: 75,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/142.png',
      description: 'It has wings. It uses them to fly at high speeds.'
    },
    {
      name: 'Snorlax',
      type: 'Normal',
      height: 2.1,
      weight: 460.0,
      hp: 160,
      attack: 110,
      defense: 65,
      speed: 30,
      specialAttack: 65,
      specialDefense: 110,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/143.png',
      description: 'It sleeps most of the time. It uses its bulk to block paths.'
    },
    {
      name: 'Articuno',
      type: 'Ice/Flying',
      height: 1.7,
      weight: 55.4,
      hp: 90,
      attack: 85,
      defense: 100,
      speed: 85,
      specialAttack: 95,
      specialDefense: 125,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/144.png',
      description: 'It has icy wings. It uses them to create blizzards.'
    },
    {
      name: 'Zapdos',
      type: 'Electric/Flying',
      height: 1.6,
      weight: 52.6,
      hp: 90,
      attack: 90,
      defense: 85,
      speed: 100,
      specialAttack: 125,
      specialDefense: 90,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/145.png',
      description: 'It has electric wings. It uses them to create lightning storms.'
    },
    {
      name: 'Moltres',
      type: 'Fire/Flying',
      height: 2.0,
      weight: 60.0,
      hp: 90,
      attack: 100,
      defense: 90,
      speed: 90,
      specialAttack: 125,
      specialDefense: 85,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/146.png',
      description: 'It has fiery wings. It uses them to create firestorms.'
    },
    {
      name: 'Dratini',
      type: 'Dragon',
      height: 1.8,
      weight: 3.3,
      hp: 41,
      attack: 64,
      defense: 45,
      speed: 50,
      specialAttack: 50,
      specialDefense: 50,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/147.png',
      description: 'It has a small body. It uses it to shed its skin.'
    },
    {
      name: 'Dragonair',
      type: 'Dragon',
      height: 4.0,
      weight: 16.5,
      hp: 61,
      attack: 84,
      defense: 65,
      speed: 70,
      specialAttack: 70,
      specialDefense: 70,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/148.png',
      description: 'It has a long body. It uses it to fly through the air.'
    },
    {
      name: 'Dragonite',
      type: 'Dragon/Flying',
      height: 2.2,
      weight: 210.0,
      hp: 91,
      attack: 134,
      defense: 95,
      speed: 80,
      specialAttack: 100,
      specialDefense: 100,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/149.png',
      description: 'It has wings. It uses them to fly around the world.'
    },
    {
      name: 'Mewtwo',
      type: 'Psychic',
      height: 2.0,
      weight: 122.0,
      hp: 106,
      attack: 110,
      defense: 90,
      speed: 130,
      specialAttack: 154,
      specialDefense: 90,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/150.png',
      description: 'It was created by scientists. It uses its psychic powers to destroy everything.'
    },
    {
      name: 'Mew',
      type: 'Psychic',
      height: 0.4,
      weight: 4.0,
      hp: 100,
      attack: 100,
      defense: 100,
      speed: 100,
      specialAttack: 100,
      specialDefense: 100,
      imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/151.png',
      description: 'It is rare. It uses its psychic powers to transform into any Pokemon.'
    }
  ];

  console.log('Seeding Pokemon data...');

  for (const pokemon of pokemonData) {
    try {
      await prisma.pokemon.upsert({
        where: { name: pokemon.name },
        update: pokemon,
        create: pokemon,
      });
    } catch (error) {
      console.error(`Error seeding ${pokemon.name}:`, error);
    }
  }

  console.log('Pokemon seeding completed!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });